on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:
    inputs:
      pre_install_debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled before yarn install (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      post_build_debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled after build (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  tsc:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.pre_install_debug_enabled }}

    - run: yarn install --frozen-lockfile
    - run: yarn build

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.post_build_debug_enabled }}
